### ISSUE TITLE
light on value for xdim

### ISSUE THREAD

**Issue by gwijsman** [mtreinish/pymochad#5]
http://www.authinx.com/manuals/activehome/xtdcode.pdf

page 5

xdim value 3F hex (= 63 decimal = 111111 Binary) is the max value for xdim 

you are now using 255 as max but 64 is off and 63 is full brightness 
(for x10 modules that understand the xdim command)

**Comment by mtreinish** [comment]
Thanks for filing a bug on this. But, I would open this bug against home assistant instead of pymochad. This issue is strictly a bug in home assistant since pymochad doesn't actually dictate a brightness value it just provides an interface for something like home assistant to send commands to a mochad daemon. Nothing in pymochad actually says the max value for brightness is 255. It just provides a send_cmd() function that xdim can be used with.

That being said, this max value is actually a device specific thing. According to the mochad docs there are devices out there which use 0-33, 0-63, and 0-255. 

https://sourceforge.net/p/mochad/code/ci/master/tree/README#l82
https://sourceforge.net/p/mochad/discussion/1320002/thread/b1841348/a809/attachment/mochad_usage.pdf

This is a problem on X10 in general where the standard is very loose and a lot of behavior changes between devices.The proper answer here is probably to add a config flag to the mochad light component in home-assistant.

This also seems related to https://github.com/home-assistant/home-assistant/issues/8943 where the home-assistant mochad light component is in general not working.

**Comment by gwijsman** [comment]
I agree
